baseURL = "https://tieguanyin-dev.github.io/tieguanyindev/"
languageCode = "en-us"
title = "Tieguanyin Tea Stories"
theme = "hello-coolapso"

[params]
  description = "A Hugo website about tea, Guanyin, and the origin of Tieguanyin tea."
